en:
  languageName: English
  weight: 1
  ### copyright (markdown can be used) ###
  copyright: "Copyright &copy; {{< current_year >}} austinte.ch. All Rights Reserved. [Dot Org Theme](https://github.com/cncf/dot-org-hugo-theme) for Hugo by [CNCF](https://www.cncf.io)."
  title: "leaders.austinte.ch"
  description: "Community - focused events for technologists in the Austin, TX area. No vendor pitches, just content by and for individual contributors and people leaders who want a rising tide to lift all boats."
  params:
    ### accessibility ###
    accessibility:
      skip_text: "Skip to content"
      help_text: "Accessibility Statement"
      help_url: "/about/"
    ### calls to action ###
    main_cta:
      text: "Join us in March"
      link: "/mvp/"
    footer_cta:
      text: "Mailing List"
      link: "/mailing-list/"
    github_edit: "Edit this page on GitHub"
  ### example menu showing children ###
  menu:
    main:
    - identifier: "about"
      name: "About"
      url: "/about/"
      weight: 1

    - identifier: "upcoming"
      name: "Upcoming Events"
      url: "/upcoming/"
      weight: 2

    - identifier: "mvp"
      name: "The MVP, March 2nd 2024"
      url: "/mvp/"
      weight: 1
      post: "Join us for our inaugural event on March 2nd"
      parent: "upcoming"
    - identifier: "cloudaustin"
      name: "CloudAustin Meetup"
      url: "/cloud-austin/"
      weight: 2
      post: "The Cloud Austin Meetup runs once per month. Join us!"
      parent: "upcoming"
    - identifier: "austindevops"
      name: "Austin DevOps Meetup"
      url: "/austin-devops/"
      weight: 3
      post: "The Austin DevOps Meetup runs once per month. Join us!"
      parent: "upcoming"
    
    - identifier: "faq"
      name: "FAQs"
      url: "/faq/"
      weight: 3

es:
  languageName: Spanish
  contentDir: content/es
  weight: 2
  title: "Título del Sitio"
  description: "Descripción del Sitio"
  menu:
    main:
    - identifier: "about"
      name: "Acerca de"
      url: "/example-page/"
      weight: 1
    - identifier: "faq"
      name: "FAQs"
      url: "/faq/"
      weight: 3
